project_name: wiretap
before:
  hooks:
    - make build-ui
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - repository:
      owner: pb33f
      name: homebrew-taps

    commit_author:
      name: goreleaserbot
      email: goreleaser@pb33f.io

    homepage: "https://pb33f.io/wiretap"
    description: "The worlds coolest OpenAPI compliance dev HTTP proxy"

    install: |
      bin.install "wiretap"

snapshot:
  name_template: "{{ .Tag }}"

upx:
  -
    # Whether to enable it or not.
    enabled: true


    # Filter by GOOS.
    #
    # Since: v1.19
    goos: [ linux , darwin ]

    # Filter by GOARCH.
    #
    # Since: v1.19
    goarch: [ arm, amd64 ]

    # Filter by GOARM.
    #
    # Since: v1.19
    goarm: [ 8 ]

    # Filter by GOAMD64.
    #
    # Since: v1.19
    goamd64: [ v1 ]

    # Compress argument.
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: best

    # Whether to try LZMA (slower).
    lzma: true

    # Whether to try all methods and filters (slow).
    brute: true
    