version: 2
project_name: wiretap
before:
  hooks:
    - make build-ui
    - go mod tidy
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
checksum:
  name_template: 'checksums.txt'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - darwin
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        wait: true
        timeout: 20m

homebrew_casks:
  - repository:
      owner: pb33f
      name: homebrew-taps

    commit_author:
      name: goreleaserbot
      email: goreleaser@pb33f.io

    homepage: "https://pb33f.io/wiretap"
    description: "The worlds coolest OpenAPI compliance dev HTTP proxy"

snapshot:
  version_template: "{{ .Tag }}"

upx:
  - enabled: true
    ids:
      - default
    goos: [linux]
    goarch: [arm, amd64]
    goarm: [8]
    goamd64: [v1]
    compress: best
    lzma: true
    brute: true
